/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImageRouteImport } from './routes/image'
import { Route as ApiAiSplatRouteImport } from './routes/api.ai.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageRoute = ImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSplatRoute = ApiAiSplatRouteImport.update({
  id: '/api/ai/$',
  path: '/api/ai/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/image': typeof ImageRoute
  '/api/ai/$': typeof ApiAiSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/image': typeof ImageRoute
  '/api/ai/$': typeof ApiAiSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/image': typeof ImageRoute
  '/api/ai/$': typeof ApiAiSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/image' | '/api/ai/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/image' | '/api/ai/$'
  id: '__root__' | '/' | '/image' | '/api/ai/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImageRoute: typeof ImageRoute
  ApiAiSplatRoute: typeof ApiAiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image': {
      id: '/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/$': {
      id: '/api/ai/$'
      path: '/api/ai/$'
      fullPath: '/api/ai/$'
      preLoaderRoute: typeof ApiAiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImageRoute: ImageRoute,
  ApiAiSplatRoute: ApiAiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
